server.port=1990
spring.application.name=spring-boot-kafka-learning

app.kafka.topic.one=mohan-topic-json
app.kafka.topic.two=mohan-topic

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=true

spring.kafka.producer.one.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.one.group-id= MohanConsumerGroup-JSON
spring.kafka.consumer.one.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.one.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.one.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.one.properties.spring.json.value.default.type = com.mohankafka.springbootkafkalearning.payload.User
spring.kafka.consumer.one.properties.spring.json.trusted.packages=*
# default is true → set false to ignore headers and rely on the default type specified above
spring.kafka.consumer.one.properties.spring.json.use.type.headers = false

spring.kafka.consumer.two.group-id= MohanConsumerGroup
spring.kafka.consumer.two.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.two.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.two.properties.spring.deserializer.value.delegate.class=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.admin.bootstrap-servers=localhost:9092
